# Generated by Django 5.2.7 on 2025-11-13 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_slot', models.CharField(choices=[('12PM', '12 PM'), ('3PM', '3 PM'), ('6PM', '6 PM'), ('8PM', '8 PM'), ('9PM', '9 PM'), ('11PM', '11 PM'), ('12AM', '12 AM')], max_length=10)),
                ('date', models.DateField()),
                ('operation', models.CharField(choices=[('+', 'Add'), ('-', 'Subtract')], max_length=1)),
                ('entry_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_win', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('position', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('players', models.ManyToManyField(to='Payment_System_App.player')),
            ],
        ),
    ]
