# Generated by Django 5.2.7 on 2025-11-13 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment_System_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_slot', models.CharField(choices=[('12PM', '12 PM'), ('3PM', '3 PM'), ('6PM', '6 PM'), ('8PM', '8 PM'), ('9PM', '9 PM'), ('11PM', '11 PM'), ('12AM', '12 AM')], max_length=10)),
                ('screenshot', models.ImageField(upload_to='match_results/')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
